version: "2.7"

services:
  modernjs:
    image: modernjs
    build: .
    user: node
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/babel_webpack_starter
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w /api/db.json
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api