version: "2.7"

services:
  reactjs:
    build: .
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    command: npm run start
